### ISSUE TITLE
Apollo client proxy is getting blocked by CORS policy when fetching from backend.

### ISSUE THREAD

**Issue by smehltrett** [react-cosmos/react-cosmos-classic#10]
### Unable to get cors configured in cosmos for apollo client.

I am trying to setup the cosmos apollo proxy to fetch live data from our gql backend within comps. The cors policy on the backend is enabled and configured for our normal app environment and localhost:8989 has been added to the whitelist for cosmos. I have tried using the same client configuration options as our live site but I am still getting blocked on the pre-flight request. The same client configuration works just fine when running the normal app locally but I cannot get this to work within cosmos no matter what I seem to try. 

_Access to fetch at 'https://backenddomain' from origin 'http://localhost:8989' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

The app is a create react app and cosmos is configured to use the same react-scripts/config/webpack.config file as the app.

I have tried adjusting the credentials property on the apollo client config but all options seem to get the same result. The only difference I see on the options request made from the full app running locally and the cosmos options request is that the Sec-Fetch-Site options from cosmos is set to cross-site and from the app its same-site. 

Any ideas on what I might be able to try to get this to work from within cosmos?

![difference](https://user-images.githubusercontent.com/5846660/84174602-a8301980-aa33-11ea-8c49-13cedbd55bc8.jpg)

**Comment by ovidiuch** [comment]
Transferred issue to react-cosmos-classic repo.

@smehltrett The Apollo proxy is designed for an older version of React Cosmos, and unfortunately I don't have the knowledge to investigate. As the Apollo proxy doesn't have a dedicated maintainer to provide help anymore, your best bet is to look into [the only source file, which is pretty small](https://github.com/react-cosmos/react-cosmos-classic/blob/e65f9275fa83daf8c6816c358e73e3aa7b0c6fc8/packages/react-cosmos-apollo-proxy/src/index.js), to see if you can figure it out yourself. Good luck!

**Comment by smehltrett** [comment]
darn I even tried not using a proxy and just using both boost and full client directly in the fixture. Always seems to get blocked by cors

**Comment by smehltrett** [comment]
Finally got this sorted out. Turns out the cosmos domain was only added to the whitelist for one of the two regions we are deployed to... Of course not the region that was taking my request

**Comment by ovidiuch** [comment]
Great to hear!
